print("------Student Information--------")

student_name=input("enter student name: ")
age=int(input("enter the age: "))
city=input("enter the city: ")
college=input("enter the college: ")
course=input("enter the course:")
mobile_number=input("enter the mobile number:")
father_name=input("Enter the father name: ")
mother_name=input("Enter the mother name: ")
email=input("Enter the email: ")
percentage=float(input("Enter the percentage: "))
height=float(input("Enter the height: "))
weight=float(input("Enter the weight: "))
hobby=input("Enter the hobby: ")
favurite_language=input("Enter the favurite language: ")
blood_group=input("Enter the blood group: ")
date_of_birth=input("Enter the date of birth: ")

print("\n--------Student details--------")
print("Father Name:",father_name)
print("Mother Name:",mother_name)
print("Email:",email)
print("Percentage:",percentage)
print("Height:",height)
print("Weight:",weight)
print("Hobby:",hobby)
print("Favurite Language:",favurite_language)
print("Blood Group:",blood_group)
print("Date Of Birth:",date_of_birth)
print(f"Student_Name :{student_name}")
print(f"Age :{age}")
print(f"City :{city}")
print(f"College :{college}")
print(f"Course :{course}")
print(f"Mobile_Number :{mobile_number}")


print("\n------ Welcome ------")

print(f"Hello {student_name}")
print(f"Welcome to Python Internship Program.")
print(f"You are from {city}.")
print(f"You are studying {course} in {college}.")
print(f"Your Percentage is {percentage}%.")
print(f"After 5 Years Your Age Will Be {age + 5}.")
print("Thank You!")
